void simulate(double *xValues, int numSamples, int dim_states,
              double *u_t, int num_actions, int dim_actions,
              double dt_t,
              double *m_t, int dim_m,
              double *l_t, int dim_l,
              double *I_t, int dim_I,
              double g_t,
              double *k_t, int dim_k,
              double dst_t,
              double *outArray, int num_out, int dim_out);